
-- 查询用户表
SELECT * FROM USERS;
--删除指定记录
DELETE FROM USER WHERE ID = 1000
--添加记录
INSERT INTO USER(NAME,TITLE) VALUES('XIAOMING','LAOLANG');

--建表语句
CREATE TABLE USERS (
ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1000, INCREMENT BY 1 ),
NAME VARCHAR(24) NOT NULL,
PASSWORD VARCHAR(64),
USER_TYPE VARCHAR(12),
TELEPHONE VARCHAR(11),
ADDRESS VARCHAR(512),
NATIONALITY VARCHAR(24),
PHOTO BLOB,
LITERATURE_NUM INT DEFAULT 0,
DELETE_NUM INT DEFAULT 0,
UPLOAD_TIME TIMESTAMP,
PRIMARY KEY (ID)
);

--文件表
CREATE TABLE FILES(FILE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1 ),
	TITLE VARCHAR(512) NOT NULL,
	FILE_TYPE VARCHAR(12),
	CONTENT CLOB,
	ATTACH_NUM VARCHAR(512),
	UPLOAD_TIME TIMESTAMP,
	DELETE_TIME TIMESTAMP,
	USER_ID INTEGER,
	PRIMARY KEY (FILE_ID)
);

--附件表
CREATE TABLE ATTACHMENT(ATTACH_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 9000, INCREMENT BY 1 ),
	FILE_ID INTEGER NOT NULL,
	USER_ID INTEGER,
	ATTACH_NAME VARCHAR(512),
	PATH VARCHAR(128),
	DELETE_FLAG INTEGER DEFAULT 0, 
	UPLOAD_TIME TIMESTAMP,
	DELETE_TIME TIMESTAMP,
	PRIMARY KEY (ATTACH_ID)
);
--添加字段
ALTER TABLE USERS ADD COLUMN TELEPHONE VARCHAR(24)


--器材仪器表
CREATE TABLE APPARATUS (APPA_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 6000, INCREMENT BY 1 ),
	APPA_NAME VARCHAR(512),
	PATH VARCHAR(128),
	DEPT VARCHAR(128),
	MANAGER VARCHAR(128),
	STATUS VARCHAR(10),
	PRICE INTEGER DEFAULT 0, 
	ROLE INTEGER ,
	TYPE INTEGER 
	IMPORT_TIME TIMESTAMP,
	PRIMARY KEY (APPA_ID)
);

--新闻信息表
CREATE TABLE NEWS (NEWS_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1 ),
	TITLE VARCHAR(512),
	PUBLISH_TIME TIMESTAMP,
	CONTENT CLOB,
	PRIMARY KEY (NEWS_ID)
);

--文档表
CREATE TABLE DOCUMENTS(
DOC_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1 ),
TITLE VARCHAR(124),
USER_ID INTEGER,
PATH VARCHAR(124),
UPLOAD_TIME TIMESTAMP,
PRIMARY KEY (DOC_ID)
)

--留言表
CREATE TABLE MESSAGE(
	MSG_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 10000, INCREMENT BY 1 ),
	NAME VARCHAR(24),
	GENDER VARCHAR(10),
	EMAIL VARCHAR(36),
	CONTENT VARCHAR(124),
	UPLOAD_TIME TIMESTAMP,
	PRIMARY KEY (MSG_ID)
)
